[project]
name = "camoufox-server"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "camoufox[geoip]>=0.4.11",
    "fastapi>=0.121.2",
    "pydantic>=2.12.4",
    "scalar-fastapi>=1.4.3",
    "uvicorn>=0.38.0",
]
